### ISSUE TITLE
Common Pointers for all the jobs in the queue.

### ISSUE THREAD

**Issue by vihari** [Pithikos/C-Thread-Pool#1]
In the function thpool_add_work of thpool.c the assignmenet of the newJob is as follows:
newJob->arg=arg_p
where arg_p is the argument of the function.
This leads to a situation in which all the jobs in the queue having the same pointer.
This can be mitigated by replacing the lines with:

newJob->arg=(char*)malloc(10000*sizeof(char));
strcpy(newJob->arg,arg_p);

but this way we lose the obscureness of the API.

**Comment by Pithikos** [comment]
I mark this as closed. If you have any further inqueries, feel free to reopen!
