### ISSUE TITLE
Remove exit(1)

### ISSUE THREAD

**Issue by Pithikos** [Pithikos/C-Thread-Pool#12]
There are a bunch of exit(1) that occur in the code. This is a bad design for a library since it takes control away from the user.

Instead of exit(1) returning specific error codes should be used.

**Comment by Pithikos** [comment]
This should be fixed now by marioli: https://github.com/Pithikos/C-Thread-Pool/pull/19

**Comment by marwankallal** [comment]
What do you think about using return codes for functions that just `exit(1)`?
It shouldn't break backwards compatibility either, they can just ignore the return value.

**Comment by Pithikos** [comment]
@marwankallal yes, if this is to be implemented that is the way to go about it.

**Comment by boxerab** [comment]
If this pool is being used in another application, it would be nice to remove exit() and let the application decide what to do .

**Comment by marwankallal** [comment]
There's a PR (#28) that should do this

**Comment by Pithikos** [comment]
Thanks marwankallal. I merged the pull request now. However I keep this open since I think for the future some more specific error codes need to be defined.

**Comment by marwankallal** [comment]
Sounds good. I think it would make sense to make a new issue with specifically return codes/error handling, just for organizational purposes. 

If you agree, I can make the new one.

**Comment by Pithikos** [comment]
Yes, sure. Feel free to do so.

**Comment by Pithikos** [comment]
Reported at https://github.com/Pithikos/C-Thread-Pool/issues/30
