### ISSUE TITLE
Malloc-ing more than needed memory

### ISSUE THREAD

**Issue by fushijian** [Pithikos/C-Thread-Pool#21]
the code in thpool.c at 143 lines is as blow:
   	thpool_p->threads = (struct thread**)malloc(num_threads * sizeof(struct thread));

i think it shuold be   
         thpool_p->threads = (struct thread**)malloc(num_threads * sizeof(struct thread *));

**Comment by Pithikos** [comment]
Nice catch! This definitely is a bug.

**Comment by boxerab** [comment]
+1 for merging this fix into master
