### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 719Ben** [Pithikos/C-Thread-Pool#33]
Could you please include a license for the project?

**Comment by Pithikos** [comment]
Hi Ben, at the moment the license can be found at the [header file](https://github.com/Pithikos/C-Thread-Pool/blob/master/thpool.h). So I assume your suggestion is to have the license at other places so it's more visible. Any specific place you have in mind?

**Comment by 719Ben** [comment]
Thanks for the quick response. I think having it in the top of the repository would be great.
Shown in: https://github.com/Pithikos/C-Thread-Pool/pull/34
