### ISSUE TITLE
want to add multiple tasks to thread pool using same function with different args

### ISSUE THREAD

**Issue by jiych** [Pithikos/C-Thread-Pool#36]
hi,i want to do smt like this
```

  for (i=0; i<2; i++){
                j = snprintf(fn,sizeof(fn),"./xa%c",'a'+i); 

                fn[j] = '\0';

                printf("fn=%s\n",fn);

                thpool_add_work(thpool, (void*)task, (void*)fn);

        };  
```
`fn` is file name,but it seems two tasks in thread pool deal with the second `fn`,that is `./xab`

**Comment by myseemylife** [comment]
obviously！fn is shared by two thread,when task run .they always see the same things!

**Comment by Pithikos** [comment]
You probably need to change your function to make it thread-safe. There are many ways to do this but the easiest thing is by having the function not mutating any state but rather creating a new item each time.
