### ISSUE TITLE
Problem at initlize thpool with num = 0

### ISSUE THREAD

**Issue by wow2006** [Pithikos/C-Thread-Pool#37]
I just missing around with clang analyzer

using 

`clang --analyze -Xanalyzer -analyzer-output=text thpool.c`

```
thpool.c:140:39: warning: Call to 'malloc' has an allocation size of 0 bytes
        thpool_p->threads = (struct thread**)malloc(num_threads * sizeof(struct thread *));
```

Hope to Help

**Comment by Pithikos** [comment]
I am not sure what the analyser does, but what would the use be to initialize the threadpool to 0?

In any case if a threadpool of 0 threads is being initialized an error code should be returned.

**Comment by wow2006** [comment]
It is static analyse and i knew it don't make sense but I just want to help.

**Comment by Den68** [comment]
Work arround for clang, questions:
````
malloc(
((num_threads > 0) ? (num_threads * sizeof(struct thread *)) : (sizeof(struct thread *)));

````
