### ISSUE TITLE
getting error  cannot convert to a pointer type when passing a struct as args 

### ISSUE THREAD

**Issue by vinodchoudary** [Pithikos/C-Thread-Pool#42]
my code requires me to pass a struct to task for the threads and i get this error
convert to a pointer type

My code is 

struct Tuple {
    int a;
    int b;
};
 void searchTree(struct Tuple exvals)

{
int e1 ,e2;
	e1 = exvals.a;
	e2 = exvals.b;
..............
}
 void  main(int argc, char *argv[])
{
struct Tuple expandVals;
 expandVals = searchANode(currnode);//another function
       
thpool = thpool_init(numThreads);
thpool_add_work(thpool, (void*)searchTree, (void*)expandVals);

	puts("Killing threadpool");
	thpool_destroy(thpool);
}

**Comment by Pithikos** [comment]
Which exactly is the error code?

**Comment by vinodchoudary** [comment]
In function ‘main’:
p3d.c:163:9: error: cannot convert to a pointer type
         thpool_add_work(thpool, (void*)searchTree, (void*)expandVals);

**Comment by Pithikos** [comment]
Have a look at the example at https://github.com/Pithikos/C-Thread-Pool/blob/master/example.c and the tests at https://github.com/Pithikos/C-Thread-Pool/tree/master/tests/src

You need to pass a pointer to void. In your case I assume something like `(void*)searchTree`

**Comment by vinodchoudary** [comment]
My code is this and I followed the example and passed void pointer to both the function and argument which in my case is a struct
truct Tuple {
int a;
int b;
};
void searchTree(struct Tuple exvals)

{
int e1 ,e2;
e1 = exvals.a;
e2 = exvals.b;
..............
}
void main(int argc, char *argv[])
{
struct Tuple expandVals;
expandVals = searchANode(currnode);//another function

thpool = thpool_init(numThreads);
thpool_add_work(thpool, (void*)searchTree, (void*)expandVals);

puts("Killing threadpool");
thpool_destroy(thpool);
}

**Comment by vinodchoudary** [comment]
Issue resolved ,
