### ISSUE TITLE
save trained model with non-C++11

### ISSUE THREAD

**Issue by ardeal** [Pithikos/C-Thread-Pool#53]
Hi patrikhuber,

I noticed that you used C++11 lib cereal to serialize the trained model and save it to binary file.
you use the following code to save the model:
void save_detection_model(detection_model model, std::string filename)
{
	std::ofstream file(filename, std::ios::binary);
	cereal::BinaryOutputArchive output_archive(file);
	output_archive(model);
};

My question is:
do you have any other substitute solution that doesn't use C++11 syntax about how to save/load the model to/from files?
can you share non-C++11 code about how to save/load the model?

**Comment by Pithikos** [comment]
I am not sure Patrik Huber is here. Maybe you were trying to post this somewhere else?

**Comment by ardeal** [comment]
sorry！
I posted the issue in the wrong git repository.
