### ISSUE TITLE
Mac Os Warning: implicit declaration of function 'pthread_setname_np'

### ISSUE THREAD

**Issue by dvirsky** [Pithikos/C-Thread-Pool#55]
Compiling thpool on Mac Os with lldb 370.0.42 triggers the above message.

```
cc -Wall -D_GNU_SOURCE -std=gnu99 -O2 -g  -c -o dep/thpool/thpool.o dep/thpool/thpool.c
dep/thpool/thpool.c:298:3: warning: implicit declaration of function 'pthread_setname_np' is invalid in C99
      [-Wimplicit-function-declaration]
  pthread_setname_np(thread_name);
  ^
```

Removing 
```c
#define _POSIX_C_SOURCE 200809L
```
which was added in a3916021c837e4892667e02e1681437ddc362725 gets rid of the warning, and passes on Linux as well.

Any hint on how to fix this warning? Is it safe to just comment out the _POSIX_C_SOURCE line?

**Comment by Pithikos** [comment]
I can't really recall exactly the reasoning behind it (my commit should probably be more informative). 

However my gut feeling is that the macro is overriding existing information in your case. Do you think you can try the below on a Mac and see if it solves it?

```
#if ! defined(_POSIX_C_SOURCE)
#define _POSIX_C_SOURCE 200809L
#endif
```

**Comment by dvirsky** [comment]
@Pithikos nope, same results. 

cc: @mnunberg

**Comment by mnunberg** [comment]
the way these macros normally work is that they make your compiler run in a specific 'mode'. According to the POSIX standard (http://pubs.opengroup.org/onlinepubs/007904975/functions/xsh_chap02_02.html):

> Additional symbols not required or explicitly permitted by IEEE Std 1003.1-2001 to be in that header shall not be made visible, except when enabled by another feature test macro.

**Comment by mnunberg** [comment]
FWIW, this is what's on my system. All the `_np` decls are guarded by this. It seems you might have luck with `_DARWIN_C_SOURCE`.

```
#if (!defined(_POSIX_C_SOURCE) && !defined(_XOPEN_SOURCE)) || defined(_DARWIN_C_SOURCE)

/* returns non-zero if pthread_create or cthread_fork have been called */
__OSX_AVAILABLE_STARTING(__MAC_10_4, __IPHONE_2_0)
int pthread_is_threaded_np(void);
```

**Comment by moe123** [comment]
```C #	if defined(__APPLE__)
#		include <AvailabilityMacros.h>
#	else
#		ifndef _POSIX_C_SOURCE
#			define _POSIX_C_SOURCE 200809L
#		endif
#	endif ```

**Comment by nil0x42** [comment]
Hi ! I'm having the same warning
