### ISSUE TITLE
merge conflict in comment at thpool.c:459

### ISSUE THREAD

**Issue by edsnowden** [Pithikos/C-Thread-Pool#62]
Looks like there's some kind of accidental merge conflict in a comment:

https://github.com/Pithikos/C-Thread-Pool/blob/430251cb657f82c9a94d4ed72db6f5ea2e30f5d9/thpool.c#L459

```
/* Get first job from queue(removes it from queue)
<<<<<<< HEAD
 *
 * Notice: Caller MUST hold a mutex
=======
>>>>>>> da2c0fe45e43ce0937f272c8cd2704bdc0afb490
 */
```

**Comment by Pithikos** [comment]
Seems to not be an issue anymore
