### ISSUE TITLE
Add more job than threads

### ISSUE THREAD

**Issue by Jamesluo1** [Pithikos/C-Thread-Pool#71]
if much job are added into queue, and now the threads are busy , no thread is waiting the mutex, so if the threads finish the work, it will not be notified again.

**Comment by xiaoyanhao** [comment]
@Jamesluo1 
If there are more jobs waiting in the queue, the semaphore value should be always `1`.
```c
static void jobqueue_push(jobqueue *jobqueue_p, struct job *newjob)
{
    // ...
    bsem_post(jobqueue_p->has_jobs); // set 1 to semaphore value and signal
    // ...
}
```

When one of the threads finish the work, it won't wait for a condition variable but continues to pull a job from the queue and execute it. In the meantime, the semaphore value will be set to `1` again.
```c
static void bsem_wait(bsem *bsem_p)
{
    pthread_mutex_lock(&bsem_p->mutex);
    while (bsem_p->v != 1) // 1. skip
    {
        pthread_cond_wait(&bsem_p->cond, &bsem_p->mutex);
    }
    bsem_p->v = 0; // 2. reset 0 to semaphore value
    pthread_mutex_unlock(&bsem_p->mutex);
}

static struct job * jobqueue_pull(jobqueue *jobqueue_p)
{
    // ...
    /* more than one job in queue -> post it */
    bsem_post(jobqueue_p->has_jobs); // 3. set 1 again
    // ...
}
```
