### ISSUE TITLE
why need pause and resume?

### ISSUE THREAD

**Issue by dpingk** [Pithikos/C-Thread-Pool#72]
Hi,
I see those two api in tests, and if I add work from client requests through TCP like below,
(implemented in main thread)
`
switch ...
{
case 1:
    thpool_add_work(thpool, (void *)get_time, (void *)local);
case 2:
    thpool_add_work(thpool, (void *)get_file, (void *)local);
`

In this case, do I need paUse and resume to surround those add works?
If these needed, how to ? and sleep also needed too ?

**Comment by Pithikos** [comment]
In the case of a client/server, you probably don't need to bother with pause/resume
