### ISSUE TITLE
unconditional (forced) destroy of thread pool

### ISSUE THREAD

**Issue by acoader** [Pithikos/C-Thread-Pool#74]
Hello,
Is there an API to destroy a pool without waiting for executing threads to complete?
Or is it easy to create one based on the current destroy API ? (thpool_destroy)
Thanks.

**Comment by Pithikos** [comment]
It doesn't exist at the moment. But this could be implemented as a flag to `thpool_destroy` I think or alternatively as a separate function `thpool_force_destroy`
