### ISSUE TITLE
thpool.c has leftovers after some merge

### ISSUE THREAD

**Issue by WSSDude** [Pithikos/C-Thread-Pool#86]
At line 459 inside thpool.c, we can see there is some forgotten leftovers after some merge.

```
/* Get first job from queue(removes it from queue)
<<<<<<< HEAD
 *
 * Notice: Caller MUST hold a mutex
=======
>>>>>>> da2c0fe45e43ce0937f272c8cd2704bdc0afb490
 */
```

It seems to be contained inside /* */ so that is why it may have been unnoticed till now (code compiles just fine with this being in).

**Comment by Pithikos** [comment]
Fixed with https://github.com/Pithikos/C-Thread-Pool/pull/75
