### ISSUE TITLE
Fix for jobqueue_init

### ISSUE THREAD

**Issue by phr35** [Pithikos/C-Thread-Pool#9]
Hi,
Very nice work ! Thanks :-)

May I suggest 2 little fixes for jobqueue_init :

static int jobqueue_init(thpool_\* thpool_p){

```
thpool_p->jobqueue_p = (struct jobqueue*)malloc(sizeof(struct jobqueue));
if (thpool_p->jobqueue_p == NULL){
    return -1;
}
```

// fix1 : pthread_mutex_init should be called after testing thpool_p->jobqueue_p
    pthread_mutex_init(&(thpool_p->jobqueue_p->rwmutex), NULL);

// fix2 : thpool_p->jobqueue_p->len should be initialized because it's used by jobqueue_clear (the condition in the while loop)
    thpool_p->jobqueue_p->len=0 ;

```
thpool_p->jobqueue_p->has_jobs = (struct bsem*)malloc(sizeof(struct bsem));
if (thpool_p->jobqueue_p->has_jobs == NULL){
    return -1;
}
bsem_init(thpool_p->jobqueue_p->has_jobs, 0);

jobqueue_clear(thpool_p);
return 0;
```

}

**Comment by Pithikos** [comment]
Thanks for the feedback!

**Comment by Pithikos** [comment]
These have now been resolved. With commit @da2c0fe45e43ce0937f272c8cd2704bdc0afb490 the jobqueue doesn't need to be allocated and thus fix1 is not needed anymore.
